application: restfultornado 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP

handlers:
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images

- url: /.*
  script: main.application

builtins:
- remote_api: on
